#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <version>"
  exit 1
fi

VERSION=$1

if [ -d "content/$VERSION" ]; then
  read -p "Version $VERSION already exists. Do you want to recreate it? (y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Removing existing version..."
    rm -rf "content/$VERSION"
  else
    echo "Exiting."
    exit 0
  fi
fi

echo "Creating new release version $VERSION"

echo "Creating new branch: release/$VERSION"
# git checkout -b "release/$VERSION"

echo "Creating new release directory..."
cp -r content/dev "content/$VERSION"

echo "Updating getting started button..."
# Read the file content
content=$(cat content/_index.md)
# Replace the version
new_content=$(echo "$content" | sed -E "s/\/mke-docs\/[0-9]+\.[0-9]+\.[0-9]+\/getting-started\//\/mke-docs\/$VERSION\/getting-started\//")
# Write the new content back to the file
echo "$new_content" > content/_index.md

echo "Done."
